---

#---------------------------------------------------
# Add a host (and alternatively a group) to the
# ansible-playbook in-memory inventory
#---------------------------------------------------
- name: Add master/bastion to created_vms group
  add_host:
    name={{ item.ip }}
    groups=created_vms
    instance_name={{ item.name }}
  with_items:
    - { name: '{{ ec2_master_tag }}', ip: '{{ master_public_ip }}' }
    - { name: '{{ ec2_bastion_tag }}', ip: '{{ bastion_public_ip }}' }

- name: Add nodes to created_vms group
  add_host:
    name={{ item.public_ip }}
    groups=created_vms
    instance_name=node{{ item.index }}
  with_items: "{{ nodes_ip }}"

- name: Add master to created_nodes group
  add_host:
    name={{ item.ip }}
    groups=created_nodes
    instance_name={{ item.name }}
  with_items:
    - { name: '{{ ec2_master_tag }}', ip: '{{ master_public_ip }}' }

- name: Add nodes to created_nodes group
  add_host:
    name={{ item.public_ip }}
    groups=created_nodes
    instance_name=node{{ item.index }}
  with_items: "{{ nodes_ip }}"
