---
# tasks file for graphical
- when: graphical == 'true'
  block:

  - name: Gather package facts
    package_facts:
      manager: auto

  - name: Gather service facts
    service_facts:

  - name: Install GUI components
    yum:
      name:
      - "@gnome-desktop"
      - "@x11"
      - "@fonts"
      exclude: "fwupdate-efi"
      skip_broken: "yes"
      state: present

  - name: Install XRDP server and dependencies
    yum:
      name:
      - "xrdp"
      - "xrdp-selinux"
      - "xorgxrdp"
      - "tigervnc-server"
      state: latest

  - name: Install xrdp configuration
    copy:
      dest: "/etc/xrdp/xrdp.ini"
      src: "xrdp.ini"
      mode: 0644

  - name: Create SELinux dir
    file:
      group: "{{ system_user }}"
      owner: "{{ system_user }}"
      mode:  0700
      path:  "/home/{{ system_user }}/.selinux"
      state: directory

  - name: Copy over SELinux modules for colord
    copy:
      src:   "{{ item }}"
      dest:  "/home/{{ system_user }}/.selinux"
      group: "{{system_user}}"
      owner: "{{system_user}}"
      mode:  0600
    with_items:
      - colord-add.pp
      - colord-add.te
    register: result

  - name: Copy over polikt config for colord
    copy:
      src:   "02-allow-colord.rules"
      dest:  "/etc/polkit-1/rules.d/02-allow-colord.rules"
      group: "root"
      owner: "root"
      mode:  0644

  - name: Update SELinux for colord
    command: semodule -i colord-add.pp chdir=/home/{{ system_user }}/.selinux
    notify: colord
    when: result.changed

#  - name: Configure XRDP for SELinux
#    file:
#      path: "{{ item }}"
#      setype: "bin_t"
#    with_items:
#    - "/usr/sbin/xrdp"
#    - "/usr/sbin/xrdp-sesman"

  - when: ansible_facts.packages["firewalld"] is defined
    block:
  
    - name: open XRDP port in firewalld (permanent)
      firewalld:
        port: "3389/tcp"
        state: enabled
        permanent: yes
  
    - name: open XRDP port in firewalld (immediate)
      firewalld:
        port: "3389/tcp"
        state: enabled
        immediate: yes
      when: ansible_facts.services["firewalld.service"].state == "running"
    
  - when: ansible_facts.packages["firewalld"] is undefined
    block:

    - name: open XRDP port in iptables
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 3389
        jump: ACCEPT
      when: ansible_facts.services["firewalld.service"].state == "running"

  - name: Enable XRDP auto-start
    service:
      name: "xrdp"
      enabled: "yes"
      state: started

...
