# file: roles/openshift.prereq/tasks/atomic.yml
---

- name: Upgrade the atomic host platform to the latest version (atomic host upgrade)
  shell: atomic host upgrade
  tags:
    - atomic

- name: Reboot the host
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true
  tags:
    - atomic

- name: Waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  sudo: false
  tags:
    - atomic

- name: get EC2 Facts
  action: ec2_facts

- debug: var=hostvars

- name: Template inventory file to host
  template: dest=/home/{{ ec2_default_user }}/inventory_ose  src=inventory_ose.j2
  tags:
   - atomic
