# file: roles/openshift.prereq/tasks/hosts.yml
---

- name: Change access permissions of key pair for master
  file:
    path: /home/{{ ec2_default_user }}/.ssh/{{ ec2_keypair }}
    mode: 0400
  tags:
    - network

- name:  Permanently set hostname for EC2 host
  shell: "echo -e 'preserve_hostname: true' | tee --append /etc/cloud/cloud.cfg > /dev/null"
  tags:
    - network

- name: Write hostname to hosts file - static table lookup
  shell: "echo -e '{{ inventory_hostname }}' | tee /etc/hostname > /dev/null"
  tags:
    - network

- name: Append hostname to networks file - describe symbolic names for networks
  shell: "echo -e 'HOSTNAME={{ inventory_hostname }}' |  tee --append  /etc/sysconfig/network > /dev/null"
  tags:
    - network

- name: Gather facts
  action: ec2_facts
  register: ec2_facts
  when: openshift_cloudprovider_kind == "aws"
  tags:
    - network

- name: Append public ipv4 to hosts file
  shell: "echo -e '{{ ec2_facts.ansible_facts.ansible_ec2_public_ipv4 }} {{ inventory_hostname }}' | tee --append /etc/hosts > /dev/null"
  when: openshift_cloudprovider_kind == "aws"
  tags:
    - network

- name: Append hostname to localhost entry of hosts file
  shell: "sed 's/127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4/127.0.0.1 {{ inventory_hostname }} localhost.localdomain localhost4 localhost4.localdomain4/w output' /etc/hosts"
  tags:
    - network

- name: Reboot the host
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true
  tags:
    - network

- name: Waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=420
  sudo: false
  tags:
    - network

- name: Add subscription DNS to etc hosts (1)
  lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.183.44   xmlrpc.rhn.redhat.com'
  tags:
    - network

- name: Add subscription DNS to etc hosts (2)
  lineinfile: dest=/etc/hosts state=present insertafter=EOF line='23.204.148.218   content-xmlrpc.rhn.redhat.com'
  tags:
    - network

- name: Add subscription DNS to etc hosts (3)
  lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.183.49   subscription.rhn.redhat.com'
  tags:
    - network

- name: Add RH docker registry to etc hosts (4)
  lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.182.63   registry.access.redhat.com'
  tags:
    - network

- name: Add jboss.org mvn repository to etc hosts (5)
  lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.182.33   repository.jboss.org'
  tags:
    - network
