# file: roles/openshift.prereq/tasks/subscr.yml
---

#---------------------------------------------------
# Disable yum plugins
#---------------------------------------------------

- name: Disable AWS yum plugin
  lineinfile: dest=/etc/yum/pluginconf.d/amazon-id.conf regexp='^enabled' line='enabled = 0' state=present
  ignore_errors: true
  tags:
    - subscription

- name: Disable rhui-lb yum plugin
  lineinfile: dest=/etc/yum/pluginconf.d/rhui-lb.conf regexp='^enabled' line='enabled = 0' state=present
  ignore_errors: true
  tags:
    - subscription

#---------------------------------------------------
# Enable yum plugins
#---------------------------------------------------

- name: Enable product-id yum plugin
  lineinfile: dest=/etc/yum/pluginconf.d/product-id.conf regexp='^enabled' line='enabled = 1' state=present
  tags:
    - subscription

- name: Enable subscription manager yum plugin
  lineinfile: dest=/etc/yum/pluginconf.d/subscription-manager.conf regexp='^enabled' line='enabled = 1' state=present
  tags:
    - subscription

#---------------------------------------------------
# Disable yum repos
#---------------------------------------------------

- name: Disable all yum repos
  command: /usr/bin/yum-config-manager --disable *
  ignore_errors: true
  tags:
    - subscription

- name: Disable rhui yum repos
  lineinfile: dest=/etc/yum.repos.d/redhat-rhui.repo regexp='^enabled' line='enabled = 0' state=present
  ignore_errors: true
  tags:
    - subscription

- name: Disable rhui-client-config yum repo
  lineinfile: dest=/etc/yum.repos.d/redhat-rhui-client-config.repo regexp='^enabled' line='enabled = 0' state=present
  ignore_errors: true
  tags:
    - subscription

#---------------------------------------------------
# Subscribe system
#---------------------------------------------------

- name: Subscribe using customer portal activation key
  redhat_subscription: state=present activationkey='{{ activationkey }}' org_id='{{ org_id }}'
  tags:
    - subscription

- name: Disable all repos by default
  shell: subscription-manager repos --disable="*"
  tags:
    - subscription

- name: Enable the pre-requisites repos
  shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-optional-rpms" --enable="rhel-7-server-ose-"{{ openshift_release }}"-rpms"
  tags:
    - subscription

- name: Import GPG keys
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
  ignore_errors: true
  tags:
    - subscription
