---

- name: Get infrastructure details
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
  - setup-key
  - setup-vpc
  - setup-security-groups
  - setup-virtual-machines
  - setup-dns
  - setup-ssh
  - setup-host-groups
  pre_tasks:
    - name: Verify ansible version
      assert:
        that:
          - "ansible_version.major == 2"
          - "ansible_version.minor == 4"
        msg: "This script is only supported with the 2.4 version of Ansible"
    - fail: msg="Variable '{{ item }}' is not defined or is empty"
      when: (platform == 'openshift-enterprise') and ((item not in vars) or vars[item] == '')
      with_items:
        # - rhsm_username
        # - rhsm_password
        # - rhsm_pool
        - rhsm_key_id
        - rhsm_org_id

- name: Setup VM hosts
  hosts: localhost

  hosts: created_nodes
  remote_user: "{{ remote_user_name }}"
  vars:
    state: 'present'
		tasks:
    - name: Cache docker images
				  shell: /usr/bin/docker pull "{{ item }}"
				  become: true
				  with_items:
				   - kubernetes/guestbook
				   - registry.access.redhat.com/rhscl/nodejs-6-rhel7
				   - registry.access.redhat.com/rhscl/nodejs-4-rhel7
				   - registry.access.redhat.com/rhscl/php-56-rhel7
				   - registry.access.redhat.com/rhscl/php-70-rhel7
				   - registry.access.redhat.com/openshift3/jenkins-1-rhel7
				   - registry.access.redhat.com/openshift3/jenkins-2-rhel7
