---
- hosts: localhost
  become: yes

  tasks:
  - name: download and extract openshift installer
    unarchive:
      src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/openshift-install-linux-{{ openshift_version }}.tar.gz
      dest: "{{ openshift_installer_path }}"
      remote_src: yes

  - name: download and extract openshift oc cli tool
    unarchive:
      src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/openshift-client-linux-{{ openshift_version }}.tar.gz
      dest: "{{ openshift_installer_path }}"
      remote_src: yes

  - name: configure openshift oc command completion
    shell: "{{ item }}"
    loop:
      - "oc completion bash > oc_bash_completion"
      - "cp oc_bash_completion /etc/bash_completion.d/"

  - name: extract openshift odo developer cli tool
    unarchive:
      src: https://mirror.openshift.com/pub/openshift-v4/clients/odo/v{{ openshift_odo_version }}/odo-linux-amd64.tar.gz
      dest: "{{ openshift_odo_path }}"
      remote_src: yes

  - name: configure openshift odo command completion
    shell: "complete -o nospace -C {{ openshift_installer_path }} odo"
