# TODO: eval and ssh-add executed in different shell contexts
#       these commands would need to be executed together along with installer and
#       user creation actions in the playbooks 2, 3, and 4
#
#   - name: eval ssh-agent
#     shell: eval "$(ssh-agent -s)"
# 
#   - name: ssh-add cluster key
#     shell: ssh-add {{ openshift_cluster_name }}-key
---
- hosts: localhost

  tasks:
  - name: generate cluster ssh key pair
    openssh_keypair:
      path: "{{ openshift_installer_path }}/{{ openshift_cluster_name }}-key"
      size: 4096
      type: rsa

  - debug:
      msg: Sequentially run the eval and ssh-add commands below.

  - debug:
      msg: eval $(ssh-agent -s)

  - debug:
      msg: "ssh-add {{ openshift_cluster_name }}-key"