---
# teardown cluster
- hosts: localhost
  
  tasks:
  - debug:
      msg: execute the following command to teardown the openshift cluster

  - debug:
      msg: "{{ openshift_installer_path }}/openshift-install destroy cluster --dir={{ openshift_installer_path }} --log-level={{ openshift_installer_log_level }}"