# file: roles/install.openshift/tasks/install.yml
---

# - name: Gather facts
#   action: ec2_facts
#   register: ec2_facts
#   when: openshift_cloudprovider_kind == "aws"
#   tags:
#    - ansible-installer
#
# - name: Debug hostvars
#   debug: var=hostvars
#   tags:
#    - ansible-installer

- name: Template inventory file to master
  template: dest=/home/{{ ansible_user }}/inventory_ose  src=inventory_ose.j2
  tags:
   - ansible-installer

- name: Curl get pip
  become: yes
  command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" chdir=/home/{{ ansible_user }}
  - ansible-installer
  tags:

- name: Python install pip
  become: yes
  command: python /home/ec2-user/get-pip.py chdir=/home/{{ ansible_user }}
  tags:
   - ansible-installer

- name: Install passlib
  become: yes
  pip: name=passlib state=present
  tags:
   - ansible-installer

- name: Copy over key pair
  copy: dest="/home/ec2-user/.ssh/{{ ec2_keypair }}"  mode=0400  src="{{ terraform_working_dir }}/{{ ec2_keypair }}"
  tags:
   - ansible-installer

- name: Run ansible-installer (advanced method)
  shell: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory_ose /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml chdir=/home/ec2-user
  tags:
   - ansible-installer
