# file: roles/install.openshift/tasks/subscr.yml
---

- name: Subscribe using customer portal activation key
  redhat_subscription: state=present activationkey='{{ activationkey }}' org_id='{{ org_id }}'
  tags:
    - subscription

- name: Disable all repos by default
  shell: subscription-manager repos --disable="*"
  tags:
    - subscription

- name: Enable the pre-requisites repos
  shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-optional-rpms" --enable="rhel-7-server-ose-"{{ openshift_release }}"-rpms"
  tags:
    - subscription
