# file: list_active.yml
---
- name: Search for EBS volumes
  hosts: localhost
  vars:
#  - days: 5
  - dkcolor: "goldenrod"
  - email:
    - "RHG-AWS@redhat.com"
  - ltcolor: "LIGHTYELLOW"
  - mail: true
  - stop: true
  roles:
  - { role: scan-ebs, ec2_region: "us-east-1", unattached: true }
  - { role: scan-ebs, ec2_region: "us-east-2", unattached: true }
  - { role: scan-ebs, ec2_region: "us-west-1", unattached: true }
#  - { role: scan-ebs, ec2_region: "us-east-1", days: 5 }
#  - { role: scan-ebs, ec2_region: "us-east-2", days: 5 }
#  - { role: scan-ebs, ec2_region: "us-west-1", days: 5 }

- name: Search for running instances (first notice)
  hosts: localhost
  vars:
  - days: 5
  - dkcolor: "goldenrod"
  - email:
    - "RHG-AWS@redhat.com"
  - ltcolor: "LIGHTYELLOW"
  - mail: true
  - stop: false
  roles:
  - { role: scan, ec2_region: "us-east-1" }
  - { role: scan, ec2_region: "us-east-2" }
  - { role: scan, ec2_region: "us-west-1" }

- name: Search for running instances (second notice)
  hosts: localhost
  vars:
  - days: 6
  - dkcolor: "DARKORANGE"
  - email:
    - "RHG-AWS@redhat.com"
  - ltcolor: "antiquewhite"
  - mail: true
  - stop: false
  roles:
  - { role: scan, ec2_region: "us-east-1" }
  - { role: scan, ec2_region: "us-east-2" }
  - { role: scan, ec2_region: "us-west-1" }

- name: Search for running instances (final notice)
  hosts: localhost
  vars:
  - days: 7
  - dkcolor: "DARKRED"
  - email:
    - "RHG-AWS@redhat.com"
  - ltcolor: "mistyrose"
  - mail: true
  - stop: false
  roles:
  - { role: scan, ec2_region: "us-east-1", days: 7 }
  - { role: scan, ec2_region: "us-east-2", days: 7 }
  - { role: scan, ec2_region: "us-west-1", days: 7 }

...
