# file: roles/subscription_manager/tasks/main.yml
---

#---------------------------------------------------
# Subscribe to RHN
#---------------------------------------------------

#- name: Check RHN subscription status
#  command: subscription-manager status
#  register: sm_result
#  ignore_errors: True

#- name: Subscribe RHN
#  command: subscription-manager register --username="{{ username }}" --password="{{ password }}" --force
#  when: sm_result.rc != 0

#- name: Attach RHN Pool
#  command: subscription-manager attach --pool "{{ pool_id }}"
#  when: sm_result.rc != 0

- name: Subscribe to RHSM
  redhat_subscription:
    state: present
    username: "{{ username }}"
    password: "{{ password }}"
    pool: "{{ pool_id }}"
