# file: roles/subscription_manager/tasks/main.yml
---

#---------------------------------------------------
# DNS Setup
#---------------------------------------------------

- name: Add DNS entries for subscription
  blockinfile:
    path: /etc/hosts
    block: |
      209.132.183.44   xmlrpc.rhn.redhat.com
      23.204.148.218   content-xmlrpc.rhn.redhat.com
      209.132.183.49   subscription.rhn.redhat.com
      209.132.183.108  subscription.rhsm.redhat.com
      209.132.182.63   registry.access.redhat.com
      209.132.182.33   repository.jboss.org
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: EOF
  when: prep
  tags:
    - rhel

#---------------------------------------------------
# Key Installation
#---------------------------------------------------

- name: Check GPG keys
  shell: rpm -q gpg-pubkey | wc -l
  register: gpg_result
  changed_when: False
  ignore_errors: True
  when: prep
  tags:
    - rhel

- name: Import keys
  shell: rpmkeys --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
# DISABLED BECAUSE IT IS SLOW, ACROSS MANY NODES
#  rpm_key:
#    state: present
#    key: "{{ item }}"
#  with_items:
#    - /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
#    - /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  when: prep and gpg_result.stdout != "4"
  tags:
    - rhel

#---------------------------------------------------
# Subscribe to RHN
#---------------------------------------------------

- name: Check RHN subscription status
  command: subscription-manager status
  register: sm_result
  changed_when: False
  ignore_errors: True
  when: sub
  tags:
    - rhel

- name: Subscribe to RHSM
  redhat_subscription:
    state: present
    username: "{{ username }}"
    password: "{{ password }}"
    pool: "{{ pool_id }}"
  when: sub and sm_result.rc != 0
  tags:
    - rhel

#---------------------------------------------------
# Add Required Repositories
#---------------------------------------------------

- name: Check to see if requisite repos are already enabled
  become: yes
  shell: subscription-manager repos --list-enabled | egrep 'rhel-7-server-extras-rpms|rhel-7-server-optional-rpms|rhel-7-server-rpms' | wc -l
  register: smr_result
  changed_when: False
  ignore_errors: True
  when: repos
  tags:
    - rhel

- name: Disable all repos by default
  command: subscription-manager repos --disable "*"
  when: repos and smr_result.stdout != "3"
  tags:
    - rhel

- name: Enable the requisite rhel7 repos
  shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-optional-rpms"
  when: repos and smr_result.stdout != "3"
  tags:
    - rhel
