# file: 2_load.yml
---
#---------------------------------------------------
# OpenShift Pre- Installation
#---------------------------------------------------
- name: OpenShift Pre- Installation
  hosts: masters, nodes
  become: yes
  roles:
    - openshift.prereq

#---------------------------------------------------
# OpenShift Advanced Installation
#---------------------------------------------------
- name: OpenShift Advanced Installation
  hosts: masters
  roles:
    - openshift.install

#---------------------------------------------------
# Configure OpenShift Cluster
#---------------------------------------------------
- name: Configure OpenShift Cluster
  hosts: masters
  become: yes
  roles:
    - openshift.config

#---------------------------------------------------
# Wetty Installation
#---------------------------------------------------
- name: Wetty Installation
  hosts: masters, nodes
  become: yes
  roles:
    - epel
    - nodejs
    - wetty
