# file: 2_load.yml
---

- name: Wait for AWS AMIs to become initialized
  hosts: localhost
  gather_facts: no
  tasks:
    - wait_for:
        host: "{{ item }}"
        port: 22
        state: started
        timeout: 300
      with_items:
        - "{{ groups.admin_rhel_node }}"

- name: Configure repositories on admin node
  become: yes
  remote_user: ec2-user
  hosts:
    - admin_rhel_node
  gather_facts: yes
  roles:
    - role: subscription_manager 
  tasks:
  - name: install required packages
    package:
      name:
      - python3-pip
      - rsync
      state: present
  - name: install required Python packages
    pip:
      name:
      - ansible
      - boto
      - boto3
  - name: create src directory
    file:
      path: "~/src"
      state: directory
  - name: sync content to admin host
    synchronize:
      src: "{{ item }}"
      dest: "~/src/"
    with_items:
    - "{{ lookup('env','PWD') }}/../roles"
    - "{{ lookup('env','PWD') }}"

...
