# file: 3_unregister.yml
---

# Do not use with Cloud Access
- name: Unregister Nodes 
  become: yes
  hosts: all_nodes
  remote_user: ec2-user
  roles:
    - { role: unregister }

- name: Remove infrastructure
  hosts: localhost
  connection: local
  roles:
  - { role: aws.remove, tags: ["delete"] }

...
