---
# tasks file for service-mesh

- name: template values in operators
  copy:
    src: "{{ role_path }}/files/web-terminal-operator.yml"
    dest: "{{ openshift_build_path }}/web-terminal-operator.yml"

- name: install operators required for web terminal
  k8s:
    state: present
    definition: "{{ lookup('template', '{{ openshift_build_path }}/web-terminal-operator.yml') }}"
    namespace: "openshift-operators"

