# file: 2_load.yml
---

- name: Wait for AWS AMIs to become initialized
  hosts: localhost
  gather_facts: no
  tags:
    - wait
  tasks:
    - wait_for:
        host: "{{ item }}"
        port: 22
        state: started
        timeout: 300
      with_items:
        - "{{ groups.rhel_nodes }}"

- name: Subscribe system
  become: yes
  remote_user: ec2-user
  hosts:
    - rhel_nodes
  tags:
    - rhsm
  gather_facts: yes
  roles:
    - role: subscription_manager 

- name: Configure epel on nodes
  become: yes
  remote_user: ec2-user
  hosts: rhel_nodes
  tags:
    - epel
  roles:
    - role: epel

- name: Configure repositories on nodes
  become: yes
  remote_user: ec2-user
  hosts: le_node
  gather_facts: no
  tags:
    - letsencrypt
  roles:
    - role: LetsEncrypt

- name: Configure software on nodes
  become: yes
  remote_user: ec2-user
  hosts: rhel_nodes
  gather_facts: no
  tags:
    - software
  roles:
    - role: ansible.tower
    - role: firewalld
    - role: system-user
  tasks:
    - name: install LEMP stack
      package:
        name:
        - mariadb
        - mariadb-server
        - nginx
        state: latest

    - name: start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

- name: Configure web console (RHEL 7)
  become: yes
  remote_user: ec2-user
  hosts: rhel_nodes
  gather_facts: no
  tags:
    - wetty
  roles:
    - role: wetty
      when: rhel_ver == 'rhel7'

- name: Configure web console (RHEL 8)
  become: yes
  remote_user: ec2-user
  hosts: rhel_nodes
  gather_facts: no
  tags:
    - webconsole
  roles:
    - role: cockpit
      when: rhel_ver == 'rhel8'

- name: Upgrade packages
  become: yes
  remote_user: ec2-user
  hosts:
    - rhel_nodes
  tags:
    - upgrade
  roles:
    - role: upgrade

- name: Re-enable SCL repo when upgrade disables it
  become: yes
  remote_user: ec2-user
  hosts:
    - rhel_nodes
  gather_facts: yes
  tags:
    - upgrade
  roles:
    - role: subscription_manager 

#- name: Custom installations
#  become: yes
#  remote_user: ec2-user
#  hosts:
#    - rhel_nodes
#  gather_facts: yes
#  tags:
#    - custom
#  tasks:

- name: Check to make sure that the web console is listening
  become: no
  hosts:
    - rhel_nodes
  gather_facts: no
  tasks:
    - uri:
        url: "https://{{ inventory_hostname }}:9090/system"
        url_username: "{{ system_user }}"
        url_password: "{{ workshop_password }}"
        validate_certs: no
      delegate_to: localhost

...
