# file: roles/azure.cli.aws/defaults/main.yml
---
#####################################################
# Azure CLI
#####################################################
azure_cli_src: "http://aka.ms/linux-azure-cli"
azure_cli_dir: "{{ terraform_working_dir }}/azure-cli-1.0"
azure_cli_bin: "{{ azure_cli_dir }}/bin/azure"

#####################################################
# OCP Azure Deployment Repo
#####################################################
repo_name: "ocp39-azure-simple"
repo_url: "https://github.com/ajacocks/{{ repo_name }}.git"

#####################################################
# OCP Azure Deployment
#####################################################
ocp39_dir: "{{ terraform_working_dir }}/{{ repo_name }}"
