---

- name: Create public vpc
  ec2_vpc_net:
   name: "{{ vpc_tag }}"
   cidr_block: "{{ vpc_cidr_block }}"
   region: "{{ aws_region }}"
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   tags:
    Name: "{{ vpc_tag }}"
    namespace: "{{ namespace }}"
  register: vpc_facts

- name: Set vpc fact
  set_fact:
   vpc_id: "{{ vpc_facts['vpc']['id'] }}"

#---------------------------------------------------
# Subnet
#---------------------------------------------------
- name: Create public subnet
  ec2_vpc_subnet:
   vpc_id: "{{ vpc_id }}"
   cidr: "{{ public_subnet_1_cidr }}"
   az: "{{ aws_az }}"
   region: "{{ aws_region }}"
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   tags:
    Name: "{{ vpc_subnet_tag }}"
    namespace: "{{ namespace }}"
  register: subnet_facts

- name: Set subnet fact
  set_fact:
   public_subnet_id: "{{ subnet_facts['subnet']['id'] }}"

#---------------------------------------------------
# Gateway
#---------------------------------------------------
- name: Create internet gateway
  ec2_vpc_igw:
   vpc_id: "{{ vpc_id }}"
   region: "{{ aws_region }}"
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   state: "present"
  register: igw_facts

- name: Set gateway fact
  set_fact:
   igw_id: "{{ igw_facts['gateway_id'] }}"

#---------------------------------------------------
# Route Table
#---------------------------------------------------
- name: Create route table
  ec2_vpc_route_table:
   vpc_id: "{{ vpc_id }}"
   region: "{{ aws_region }}"
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   subnets:
    - "{{ public_subnet_id }}"
   routes:
    - dest: "{{ public_route_cidr_block }}"
      gateway_id: "{{ igw_id }}"
   tags:
     Name: "{{ vpc_route_tag }}"
     namespace: "{{ namespace }}"
  register: route_facts

- name: Set availability zone fact
  set_fact:
    availability_zone: "{{ subnet_facts['subnet']['availability_zone'] }}"
