---

- name: Curl get pip
  command: /usr/bin/curl 'https://bootstrap.pypa.io/get-pip.py' -O chdir={{ remote_user_home }}
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Python install pip
  command: /usr/bin/python {{ remote_user_home }}/get-pip.py chdir={{ remote_user_home }}
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Install passlib library
  pip: name=passlib state=present
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Create admin account
  htpasswd: name={{ admin_username }}  password={{ admin_password }}  path={{ htpasswd_path }}  state=present
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Add cluster role to admin account
  shell: /usr/bin/oc adm policy add-cluster-role-to-user cluster-admin {{ admin_username }}
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Create some test users
  shell: /usr/bin/htpasswd -b /etc/origin/master/htpasswd {{ student_name_prefix }}{{ item }} {{ student_pass_prefix }}{{ item }}
  with_sequence: count={{ student_count }}
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Add admin account for cockpit
  shell: /usr/sbin/useradd --home /home/{{ admin_username }} {{ admin_username }} && echo {{ admin_username }}:{{ admin_password }} | chpasswd –crypt-method=SHA512
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true
  ignore_errors: true

- name: Verify admin user account
  shell: /usr/bin/oc login https://{{ domain }}:{{ https_proxy_port }} --insecure-skip-tls-verify=false -u {{ admin_username }} -p {{ admin_password }}
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true
  ignore_errors: true
