# file: roles/install.openshift/tasks/hosts.yml
---

- name: Change access permissions of key pair for master
  file:
    path: /home/{{ ansible_user }}/.ssh/{{ ec2_keypair }}
    mode: 0400
  tags:
    - intranet

- name:  Permanently set hostname for EC2 host
  shell: "echo -e 'preserve_hostname: true' | tee --append /etc/cloud/cloud.cfg > /dev/null"
  tags:
    - intranet

- name: Write hostname to hosts file - static table lookup
  shell: "echo -e '{{ inventory_hostname }}' | tee /etc/hostname > /dev/null"
  tags:
    - intranet

- name: Append hostname to networks file - describe symbolic names for networks
  shell: "echo -e 'HOSTNAME={{ inventory_hostname }}' |  tee --append  /etc/sysconfig/network > /dev/null"
  tags:
    - intranet

- name: Gather facts
  action: ec2_facts
  register: ec2_facts
  when: openshift_cloudprovider_kind == "aws"
  tags:
    - intranet

- name: Append public ipv4 to hosts file
  shell: "echo -e '{{ ec2_facts.ansible_facts.ansible_ec2_public_ipv4 }} {{ inventory_hostname }}' | tee --append /etc/hosts > /dev/null"
  when: openshift_cloudprovider_kind == "aws"
  tags:
    - intranet

- name: Append hostname to localhost entry of hosts file
  shell: "sed 's/127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4/127.0.0.1 {{ inventory_hostname }} localhost.localdomain localhost4 localhost4.localdomain4/w output' /etc/hosts"
  tags:
    - intranet
