# file: roles/install.openshift/tasks/install.yml
---

- name: Curl get pip
  become: yes
  command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" chdir=/home/{{ ansible_user }}
  tags:
    - advanced

- name: Python install pip
  become: yes
  command: python /home/ec2-user/get-pip.py chdir=/home/{{ ansible_user }}
  tags:
   - advanced

- name: Install passlib
  become: yes
  pip: name=passlib state=present
  tags:
   - advanced

- name: Copy over key pair
  copy: dest="/home/{{ ansible_user }}/.ssh/{{ ec2_keypair }}"  mode=0400  src="{{ terraform_working_dir }}/{{ ec2_keypair }}"
  tags:
   - advanced

- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  file:
    path: /home/{{ ansible_user }}/.ssh/config
    state: touch
    mode: "u=rw,g=r,o=r"
  tags:
   - advanced

- name: Insert/update "Host" configuration block in ~/.ssh/config
  blockinfile:
    dest: /home/{{ ansible_user }}/.ssh/config
    block: |
      Host *
      IdentityFile ~/.ssh/libra
  tags:
   - advanced

- name: Touch the same file, but add/remove some permissions
  file:
    path: /home/{{ ansible_user }}/.ssh/config
    state: touch
    mode: 0400
  tags:
   - advanced

# - name: Debug enable ssh-agent
#  shell: echo "ssh-agent = $(ssh-agent)"

- name: Enable ssh-agent
  shell: eval $(ssh-agent)
  tags:
    - advanced

- name: Run advanced installation method
  shell: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -vvv -i inventory_ose /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml chdir=/home/{{ ansible_user }}
  tags:
   - advanced

# [TODO]: Apply to masters and nodes
# - name: Add entries to the exclude directive in the host’s /etc/yum.conf file when installed
#   command: atomic-openshift-excluder exclude
#   become: yes
#   when: openshift_release >= 3.4
#   tags:
#   - rhel
