---
# tasks file for ansible

- name: RHEL 7 Tasks
  block:

    - name: Install PIP
      yum:
        name: python2-pip

    - name: Install Ansible
      pip:
        name: ansible

  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: RHEL 8 Tasks
  block:

    - name: Install PIP
      yum:
        name: python3-pip

    - name: Install Ansible
      pip:
        name: ansible

  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'
