---

- name: Configure OpenShift
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # nodes_ip: "{{ lookup('file','nodes.json') | from_json }}"
    state: 'present'
  roles:
  - add-users
  - openshift-post-install
