---

- name: Configure OpenShift
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # nodes_ip: "{{ lookup('file','nodes.json') | from_json }}"
    state: 'present'
  roles:
  - openshift-install
  - add-users
  - openshift-post-install
  post_tasks:
   - name: Confirmation message
     debug:
      msg:
        - 'The script has completed successfully.'
        - 'Master public IP: {{ master_public_ip }}'
        - 'OpenShift console: https://{{ domain }}:8443'
