---

- name: Setup VM hosts
  hosts: localhost

- name: Register and update virtual machines
  hosts: created_vms
  remote_user: "{{ remote_user_name }}"
  vars:
    state: 'present'
  roles:
  - {role: register-virtual-machines, when: platform == 'openshift-enterprise'}
  - update-virtual-machines

- name: Setup Node hosts
  hosts: localhost

- name: OpenShift Prerequisites
  hosts: created_nodes
  remote_user: "{{ remote_user_name }}"
  vars:
    state: 'present'
  roles:
  - openshift-prep-install

- name: Install OpenShift
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # nodes_ip: "{{ lookup('file','nodes.json') | from_json }}"
    state: 'present'
  roles:
  - openshift-install
  post_tasks:
   - name: Confirmation message
     debug:
      msg:
        - 'The script has completed successfully.'
        - 'Master public IP: {{ master_public_ip }}'
        - 'OpenShift console: https://{{ domain }}:8443'
