---
# tasks file for roles/scan

#===============================================================================
#  Search and record IDs
#===============================================================================
- name: Initialize an empty list for our strings
  set_fact:
    instance_ids: []

- name: lookup running RHEL instances
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: "running"
  register: ec2

- name: Append instance ids to list if the instance is older than one week
  set_fact:
    instance_ids: "{{ instance_ids }} + [ '{{ item.instance_id }}' ]"
  when: "{{ (ansible_date_time.iso8601[:19] | to_datetime('%Y-%m-%dT%H:%M:%S') - item.launch_time[:19] | to_datetime('%Y-%m-%dT%H:%M:%S')).days }} > 7"
  with_items: "{{ ec2.instances }}"

- debug:
    var: instance_ids

- name: Make deployment working directory
  file:
    path: "{{ deploy_working_dir }}"
    state: directory

- name: Text instance report
  template:
    src: "instances.j2"
    dest: "{{ deploy_working_dir }}/hosts-{{ ec2_region }}"

- name: CSV instance report
  template:
    src: "instances-csv.j2"
    dest: "{{ deploy_working_dir }}/hosts-{{ ec2_region }}.csv"

...
