# file: 3_unregister.yml
---

# Do not use with Cloud Access
- name: Unregister Nodes 
  become: yes
  gather_facts: false
  hosts:
    - rhel_nodes
  remote_user: ec2-user
  roles:
    - { role: unregister }

- name: Remove infrastructure
  hosts: localhost
  connection: local
  roles:
  - { role: aws.remove, tags: ["delete"] }

- name: Remove .ssh/known_hosts entries
  hosts: localhost
  connection: local
  tasks:
  - lineinfile:
      path: "/home/{{ system_user }}/.ssh/known_hosts"
      regex: "^{{ item }},"
      state: absent
    with_items: rhel_nodes

...
