---

- name: Restart master controllers service
  service:
    name: atomic-openshift-master-controllers.service
    state: restarted
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Restart master api service
  service:
    name: atomic-openshift-master-api.service
    state: restarted
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true
