# file: site.yml
---

#---------------------------------------------------
# Terraform Providers
#---------------------------------------------------
- name: Terraform AWS Provider
  hosts: targets
  roles:
    - aws.infra

# [TODO]: Add Terraform Google Cloud Platform provider support.
# [TODO]: Add Terraform Microsoft Azure provider support.
# [TODO]: Add Atomic Host support.

...
