# file: site.yml
---

#---------------------------------------------------
# Terraform providers
#---------------------------------------------------
- name: Terraform AWS provider
  hosts: local_target
  roles:
    - { role: aws.infra.terraform, tags: ["terraform"], when: openshift_cloudprovider_kind == "aws" }

#---------------------------------------------------
# Intranet
#---------------------------------------------------
- name: Modify master hosts file
  hosts: masters, nodes
  become: yes
  roles:
    - { role: install.openshift, tags: ["intranet"] }

# ---------------------------------------------------
# OpenShift master hosts
# ---------------------------------------------------
- name: Prepare RHEL masters
  hosts: masters
  become: yes
  roles:
    - { role: install.openshift, tags: ["rhel", "subscription"], when: ec2_master_username == 'ec2-user' }

- name: Prepare Atmic Host masters
  hosts: masters
  become: yes
  roles:
    - { role: install.openshift, tags: ["atomic", "subscription"], when: ec2_master_username == 'cloud-user' }

#---------------------------------------------------
# OpenShift node hosts
#---------------------------------------------------
- name: Prepare RHEL nodes
  hosts: nodes
  become: yes
  roles:
    - { role: install.openshift, tags: ["rhel", "subscription"], when: ec2_node_username == 'ec2-user' }

- name: Prepare Atmic Host nodes
  hosts: nodes
  become: yes
  roles:
    - { role: install.openshift, tags: ["atomic", "subscription"], when: ec2_node_username == 'cloud-user' }

#---------------------------------------------------
# Ansible
#---------------------------------------------------
- name: Advanced installation
  remote_user: "{{ ec2_master_username }}"
  hosts: masters
  roles:
    - { role: install.openshift, tags: ["ansible-installer"] }
