---

- name: Provision instances
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
   - aws-provision

- name: Refresh hosts
  hosts: localhost

- name: Register hosts
  hosts: created_vms
  remote_user: "{{ remote_user_name }}"
  vars:
    state: 'present'
  roles:
    - rhel-common

- name: Refresh hosts
  hosts: localhost

- name: Install JBoss EAP
  hosts: created_nodes
  vars:
   state: 'present'
  roles:
    - jboss-standalone
