# file: roles/LetsEncrypt/tasks/main.yml
---

- name: "Install required packages for LetsEncrypt"
  package:
    name:
      - python3-botocore
      - python3-boto3
    state: latest

- name: "Create required directories in /etc/letsencrypt"
  file:
    path: "/etc/letsencrypt/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=x,o=x
  with_items:
  - account
  - certs
  - csrs
  - keys

- name: "Generate a Let's Encrypt account key"
  shell: "openssl genrsa 4096 | tee {{ letsencrypt_account_key }}"
  args:
    creates: "{{ letsencrypt_account_key }}"

- name: "Generate Let's Encrypt private key"
  shell: "openssl genrsa 4096 | tee /etc/letsencrypt/keys/{{ domain_name }}.key"
  args:
    creates: "/etc/letsencrypt/keys/{{ domain_name }}.key"

- name: "Generate Let's Encrypt CSR"
  community.crypto.openssl_csr:
    privatekey_path: "/etc/letsencrypt/keys/{{ domain_name }}.key"
    common_name: "{{ workshop_prefix }}.node.0.{{ domain_name }}"
#    subject_alt_name: "DNS:{{ domain_name }},DNS:www.{{ domain_name }}"
    subject_alt_name: "{{ groups['rhel_nodes'] | map('regex_replace', '^', 'DNS:') }}"
    path: "/etc/letsencrypt/csrs/{{ domain_name }}.csr"

#- name: "Generate Let's Encrypt CSR"
#  shell: "openssl req -new -sha256 -key /etc/letsencrypt/keys/{{ domain_name }}.key -subj \"/CN={{ domain_name }}\" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf \"\n[SAN]\nsubjectAltName=DNS:{{ domain_name }},DNS:www.{{ domain_name }}\")) | tee /etc/letsencrypt/csrs/{{ domain_name }}.csr"
#  args:
#    executable: /bin/bash
#    creates: "/etc/letsencrypt/csrs/{{ domain_name }}.csr"

- debug:
    msg:
    - "account_key_src: {{ letsencrypt_account_key }}"
    - "account_email: {{ acme_email }}"
    - "acme_directory: {{ acme_directory }}"
    - "acme_version: {{ acme_version }}"
    - "terms_agreed: yes"
    - "challenge: {{ acme_challenge_type }}"
    - "csr: {{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
    - "dest: {{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
    - "fullchain_dest: {{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.crt"
    - "remaining_days: 91"

- name: "Begin Let's Encrypt challenges"
  community.crypto.acme_certificate:
    account_key_src: "{{ letsencrypt_account_key }}"
    account_email: "{{ acme_email }}"
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    terms_agreed: "yes"
    challenge: "{{ acme_challenge_type }}"
    csr: "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
    dest: "{{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
    fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.crt"
    remaining_days: 91
  register: acme_challenge_your_domain

- debug:
    var: acme_challenge_your_domain

- name: "Create .well-known/acme-challenge directory"
  file:
    path: /var/www/html/.well-known/acme-challenge
    state: directory
    owner: root
    group: root
    mode: "0755"

#- name: "Implement http-01 challenge files"
#  copy:
#    content: "{{ acme_challenge_your_domain['challenge_data'][item]['http-01']['resource_value'] }}"
#    dest: "/var/www/html/{{ acme_challenge_your_domain['challenge_data'][item]['http-01']['resource'] }}"
#    owner: root
#    group: root
#    mode: "0644"
#  with_items:
#  - "{{ domain_name }}"
#  - "www.{{ domain_name }}"

- name: Challenge data
  debug:
#    msg: "User {{ item.key }} is {{ item.value['dns-01']record }} ({{ item.value['dns-01']resource_value }})"
    msg: "{{ item.key }} is {{ item.value }}"
  loop: "{{ acme_challenge_your_domain['challenge_data'] | dict2items }}"

- name: Challenge data
  debug:
    msg:
    - "{{ item.value['dns-01']['record'] }}"
    - "{{ item.value['dns-01']['resource_value'] }}"
  loop: "{{ acme_challenge_your_domain['challenge_data'] | dict2items }}"

- name: Create DNS records for LE Challenge
  route53:
    zone: "{{ domain_name }}"
    type: "TXT"
    ttl: "300"
    record: "{{ item.value['dns-01']['record'] }}"
    value: "{{ item.value['dns-01']['resource_value'] }}"
#    wait: yes
    state: present
  loop: "{{ acme_challenge_your_domain['challenge_data'] | dict2items }}"
  become: false

- name: "Complete Let's Encrypt challenges"
  community.crypto.acme_certificate:
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ letsencrypt_account_key }}"
    account_email: "{{ acme_email }}"
    challenge: "{{ acme_challenge_type }}"
    csr: "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
    dest: "{{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
    chain_dest: "{{ letsencrypt_certs_dir }}/chain_{{ domain_name }}.crt"
    fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}"
    data: "{{ acme_challenge_your_domain }}"

...
