# file: 1_aws_infra.yml
---
# https://www.terraform.io/docs/providers/aws/index.html


- name: Provision AWS Infrastucture using Terraform 
  hosts: local_target
  roles:
  - { role: aws.infra, tags: ["tf_create"] }

- name: Configure software on nodes
  become: yes
  remote_user: ec2-user
  hosts: tower_nodes
  roles:
    - { role: subscription_manager }
    - { role: epel }
    - { role: nodejs }
    - { role: wetty }
    - { role: ansible.tower }
    - { role: zsh }


# {{workshop_prefix}}.tower.<student number>.redhatgov.io:8888
# Username: ec2-user
# Password: redhat!@#