# file: roles/subscription_manager/tasks/main.yml
---

#---------------------------------------------------
# DNS Setup
#---------------------------------------------------

- name: Add DNS entries for subscription
  blockinfile:
    path: /etc/hosts
    block: |
      209.132.183.44   xmlrpc.rhn.redhat.com
      23.204.148.218   content-xmlrpc.rhn.redhat.com
      209.132.183.49   subscription.rhn.redhat.com
      209.132.183.108  subscription.rhsm.redhat.com
      209.132.182.63   registry.access.redhat.com
      209.132.182.33   repository.jboss.org
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: EOF
  tags:
    - rhel

#---------------------------------------------------
# Key Installation
#---------------------------------------------------

- name: Import keys
  shell: rpmkeys --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
# DISABLED BECAUSE IT IS SLOW, ACROSS MANY NODES
#  rpm_key:
#    state: present
#    key: "{{ item }}"
#  with_items:
#    - /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
#    - /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  tags:
    - rhel
